################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
Components/bsp/bsp_rtc.obj: ../Components/bsp/bsp_rtc.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../Configuration/smpl_nwk_config.dat" --cmd_file="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../Configuration/End_Device/smpl_config.dat" -vmspx -g -O0 --define=MRFI_CC2520 --define=__MSP430F5438A__ --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/Components/Apps" --include_path="C:/Program Files (x86)/Texas Instruments/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/Texas Instruments/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/Texas Instruments/ccsv4/msp430/include" --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../../../../../../Components/bsp" --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../../../../../../Components/bsp/boards/EXP543x" --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../../../../../../Components/bsp/drivers" --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../../../../../../Components/mrfi" --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../../../../../../Components/simpliciti/nwk"'
	@echo 'Flags (cont-d): --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../../../../../../Components/simpliciti/nwk_applications" --diag_warning=225 --silicon_errata=CPU22 --silicon_errata=CPU21 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="Components/bsp/bsp_rtc.pp" --obj_directory="Components/bsp"'
	$(shell echo --cmd_file="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../Configuration/smpl_nwk_config.dat" --cmd_file="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../Configuration/End_Device/smpl_config.dat" -vmspx -g -O0 --define=MRFI_CC2520 --define=__MSP430F5438A__ --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/Components/Apps" --include_path="C:/Program Files (x86)/Texas Instruments/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/Texas Instruments/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/Texas Instruments/ccsv4/msp430/include" --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../../../../../../Components/bsp" --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../../../../../../Components/bsp/boards/EXP543x" --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../../../../../../Components/bsp/drivers" --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../../../../../../Components/mrfi" --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../../../../../../Components/simpliciti/nwk" > "Components/bsp/bsp_rtc_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/jwang462/Desktop/Harry Summer 2016/SimpliciTI-CCS-1.1/SimpliciTI-CCS-1.1.0-F543x/Projects/Examples/EXP543x/AP_as_Data_Hub/CCE/Project/../../../../../../Components/simpliciti/nwk_applications" --diag_warning=225 --silicon_errata=CPU22 --silicon_errata=CPU21 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="Components/bsp/bsp_rtc.pp" --obj_directory="Components/bsp" >> "Components/bsp/bsp_rtc_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "Components/bsp/bsp_rtc_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "Components/bsp/bsp_rtc_ccsCompiler.opt"))
	"C:/Program Files (x86)/Texas Instruments/ccsv4/tools/compiler/msp430/bin/cl430" -@"Components/bsp/bsp_rtc_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '


